### ISSUE TITLE
Validate input values in form

### ISSUE THREAD

**Issue by PReichetanz** [PReichetanz/capstone-project#17]
## Value proposition
**As a** user
**I need** validation of my input
**to be able to** make mistakes regarding upper-/lowercase or whitespaces and punctuation, but the pupil is still found.

## Description
Wrong usage of upper-/lowercase, punctuation and whitespaces should be handled. The saved data should all have the same format.

## Acceptance Criteria

- [x]  Form component update: input validation (see below in Tasks)
- [x] Wrong upper-/lowercase of an existing pupil does not result in a second Card.
- [x] The name if the pupil is stored separately (first name, last name)

## Tasks

- [x] name input: trim, remove redundant blanks, separate into first and last name (think about "Anna-Maria Luise Muster")

[- [ ] category input: trim, uppercase first letter, lowercase other letters
- [ ] evaluation input: trim, full stop at the end, uppercase first letter, remove redundant blanks
--> removed to later issue because this is not necessary right now]
