### ISSUE TITLE
AddPupilEvaluation Page

### ISSUE THREAD

**Issue by PReichetanz** [PReichetanz/capstone-project#2]
## Value proposition
**As a** user
**I need** a way to add a pupil and a evalution
**to be able to** see all evaluations of a pupil at one place.

## Description
<img src="https://user-images.githubusercontent.com/33567019/142849352-78ae7a92-0e6e-4bca-b626-22df466434e7.png" >

## Acceptance criteria
- [x] All inputs are required fields.
- [x] If the pupil already exists, the evaluation should be added to its card at the bottom (instead of creating a new card).
- [x] The list (cards of pupils) should scroll vertically on overflow.
- [x] The DeleteButton should delete the card.

## Tasks

- [x] Form component
- [x] Card component
- [x] Integrate components into App
- [x] Setup deployment
