### ISSUE TITLE
Rating functionality for a category

### ISSUE THREAD

**Issue by PReichetanz** [PReichetanz/capstone-project#29]
Idea for first step: Submit a rating when adding a new evaluation
## Value proposition
**As a** user
**I need** to rate the pupil in the submitted category
**to be able to** choose an evaluation according to this evaluation.

## Description
![Bildschirmfoto 2021-12-06 um 09 36 13](https://user-images.githubusercontent.com/33567019/144815612-b79bb707-6418-42a1-b563-0109b0c1bd8c.png)

![Bildschirmfoto 2021-12-06 um 09 48 20](https://user-images.githubusercontent.com/33567019/144815636-64222d00-36d0-48ec-a0a8-a0a93434e691.png)

## Acceptance criteria
- [x] A new category can only be added if a rating is submitted as well.
- [x] Possible evaluations of a category are shown dependent on the chosen rating.
- [x] The evaluations use the first name of the selected pupil.
- [x] If there is no evaluation availabe, a note and button is shown to add a new one (via AddCategory Form); after submitting a new evaluation, it should be displayed at the last view of the "AddEvaluationForm".
- [x] After clicking on an evaluation, it should be highlighted (bold) so that the user knows which one he chose.

## Tasks

- [x] Refactor AddEvaluation: (1) rename "AddCategory"; (2) add rating to be saved with evaluation
- [x] Add localStorage item "Evaluations" with four default values ("Arbeiten in der Gruppe", "Arbeitsweise", "Konfliktverhalten", "Verhalten gegenüber dem Lehrer") and two default evaluations per rating
- [x] Add rating functionality with 5 options (1, 2, 3, 4, 5)  [idea here](https://reactjsexample.com/a-simple-star-rating-component-with-react/)
- [x] Refactor AddPupilForm: only the pupil can be added
- [x] Add "AddEvaluationForm" with four steps: (1) Choose a category, (2) choose a rating, (3) choose a sentence, (4) add/save to pupil's evaluations
- [x] Add different active colour to button when a category is chosen
