### ISSUE TITLE
Pupil Overview

### ISSUE THREAD

**Issue by PReichetanz** [PReichetanz/capstone-project#5]
## Value proposition
**As a** user
**I need** an overview of each pupil
**to be able to** see all its evaluations separated by category.

## Description
<img src="https://user-images.githubusercontent.com/33567019/143566094-8e060f09-d0a7-4581-8a36-105af173cc72.png">

## Acceptance Criteria

- [x] The header should display the selected pupil's name.
- [x] In "Overlay: Add Pupil", only "Name des Schülers" is required; but if an category is entered, there need to be an evaluation.
- [x] If the user adds another evaluation to an existing category, it should be added to the existing card.
- [x] The back button redirects to the previous view.

## Tasks

- [x] Header component
- [x] Navigation component (backButton optional)
- [x] Add Routing (two pages: ClassOverview and PupilOverview)
- [x] Form component update: implement grid for easier positioning (maybe header and nav component here as well?)
- [x] Form component update: needs to be controllable whether the name has to be entered or not (alternative: split in AddPupilForm and AddCategoryForm component)
- [x] Form component update: Refactor back button
