### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by PReichetanz** [PReichetanz/capstone-project#6]
## Value proposition
**As a** user
**I need** to copy the evaluations of my class / one pupil
**to be able to** paste the information somewhere else.

## Description
<img width=400 src="https://user-images.githubusercontent.com/33567019/143572339-0b495bd2-a01a-454f-a1b5-d3ccb57c5313.png">
<img width=300 src="https://user-images.githubusercontent.com/33567019/143585934-069f8acb-13f1-4d74-81e1-edcfd171c712.png">

## Acceptance criteria
- [x] When clicking on "Beurteilungen exportieren", the data is copied to clipboard.
- [x] The copied data should have the format according to picture two (it differs depending on ClassOverview and PupilOverview Page)  

## Tasks

- [x] Add button and separating line to both pages
- [x] Add copyToClipboard-Logic ([View Idea here](https://blog.logrocket.com/implementing-copy-to-clipboard-in-react-with-clipboard-api/))
